
export const SET_TEMP_STREAM = 'SET_TEMP_STREAM';
export const DEL_TEMP_STREAM = 'DEL_TEMP_STREAM';
export const ADD_STREAM = 'ADD_STREAM';
export const ADD_STREAM_REQUEST = 'ADD_STREAM_REQUEST';
export const FETCH_STREAMS = 'FETCH_STREAMS';
export const FETCH_STREAM = 'FETCH_STREAM';
export const DELETE_STREAM = 'DELETE_STREAM';
export const EDIT_STREAM = 'EDIT_STREAM';
export const REMOVE_STREAM_REQUEST = 'REMOVE_STREAM_REQUEST';

